---
title: "Trabalho de Estatística Espacial"
author: "Geanine Henriques (00323588)"
date: "`r Sys.Date()`"
output: html_document
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(readr)
library(dplyr)
library(DescTools)
library(glue)
library(sf)
library(ggplot2)
library(ggthemes)
library(ggiraph)
library(tidyverse)
library(viridis)
library(patchwork)
library(devtools)
library(zoom)
library(plotly)
```

## Banco de Dados

```{r, warning=FALSE, message=FALSE}
dados<-read_csv("cases-brazil-cities-time_2022.csv.gz")
dados<-dados%>%
  filter(state=="RN")%>%
  filter(date>"2022-10-31" & date<"2022-12-01")
total_casos<-dados%>%
  group_by(as.character(ibgeID))%>%
  summarise(casos_total=sum(newCases), city=Mode(city))
```

```{r, warning=FALSE, message=FALSE}
shape<-st_read("RN_Municipios_2021.shp")
shape$nome<-paste(shape$NM_MUN, "/", shape$SIGLA, sep="")
shape<-shape[,-(1:4)]
total_casos<-total_casos[-1,]
mapa<-merge(x=shape, y=total_casos, by=intersect('geometry', 'as.character(ibgeID)'))
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
mapa$city[mapa$city=="Lagoa d'Anta/RN"]<-"Lagoa dAnta/RN"
mapa$nome[mapa$nome=="Lagoa d'Anta/RN"]<-"Lagoa dAnta/RN"
mapa$city[mapa$city=="Olho-d'Água do Borges/RN"]<-"Olho dÁgua do Borges/RN"
mapa$nome[mapa$nome=="Olho d'Água do Borges/RN"]<-"Olho dÁgua do Borges/RN"
```

```{r, warning=FALSE, message=FALSE}
mapa$local<-as.data.frame(ifelse(mapa$nome!=mapa$city, NA, mapa$city))
mapa<-mapa%>%drop_na()
mapa$texto<-paste(mapa$nome, ":", mapa$casos_total, "casos")
```

## Gráfico e Mapa

```{r, warning=FALSE, message=FALSE}
grafico<-ggplot(mapa, 
                aes(x = reorder(nome, casos_total), 
                    y = casos_total,
                    tooltip = texto, data_id = nome)) +
  geom_col_interactive(color="lightblue", fill="darkgray", size=0.5) + 
  theme_light() +
  theme(axis.text=element_text(size = 1)) +  #<<
  labs(title = "Casos de Covid em Novembro de 2022 no RN",
       subtitle = "Fonte: https://github.com/wcota/covid19br"
  ) + ylab("") + xlab("") + coord_flip()
```

```{r, warning=FALSE, message=FALSE}
mapa<-ggplot(data=mapa, aes(fill=total_casos$casos_total), color="white") +
  geom_sf_interactive(size = 0.125, aes(data_id = nome, tooltip = nome)) +
  scale_fill_viridis_c(option="mako", name="nº de casos", direction=-1) +
  labs(x=NULL, y=NULL, 
       title="Rio Grande do Norte") + 
  theme_light()

```

```{r, warning=FALSE, message=FALSE}
girafe(ggobj = mapa + grafico, 
       width_svg = 10, height_svg = 5) %>%
  girafe_options(opts_hover(css = "fill:cyan;"))
```
